sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        yGahaMoW0W5dkATiHpwmlhog3LpWL9CVrpZ912nUOe+iBwL10+dLWVh9vqsMRNK3a8Ji93YjFmlbXvw/L7T5NdMz4g+NaNc+lsxfNq0hyu+5QeN1+WkozFLeXV9Ud34PzRT+s799jHna2ecXmPHsmkCokZTILOgO8vlAV+o6/so8ZnmaVRsQRg8Eo8SzckPc5uZFAH9mtJk6jaCxDB3RLfkeGb7GapVxW+aPrekjSpw89DR4AALcX0qXUeQercea7le1AY0tQ4F/YbdwIfSWFujKSQQafDv9Uycv2oga9UuT2ieENQRUxBFoHtDGr4G4xxqCPNh/4yZIsgcI5NwegCU2QMTQiL4DntZvhJpZXazOOW1+6bYe043C5NmpzOE5+tgNNyE0TDv7dHF04Ux68uk3Uk3mXsL/Au8AYQPvsByVww8Moc/VWaRuLPaqDtTpGBbbuaAKheZU4ftt0bTD+l7VHyoGuSDIpUW9aK6UYuSurEPXLj0i4UNhaRNg/SYRxHe75f2z218RmDEXkD7sYAAe49wjm7mbpkWUXiyiQbW/MlgkIqCGl5AqLGTbjXNJGvzNbmk8d9kn1jqK7qdCmFz6mCdzuotmt8mvodKrc5yrRhzWdc4HcCLuCgcAczWg8MhdOsG4Lw7Gzj4UITcSITKt08nbT3pmMNRJPMnLI6A=
    - secure: >-
        WXq/Dxj0ZvY99GTbwybwGbAHh/iJ4nhQ6ijJPJ2fi1/Bj2QfumaSw0e0aujeGov20gaodlG6waH42F4afAGr5O04cwCCmpXpvBUnbXEJW7xZb+k69fu7zz3y9PKW4Xpyi390lQp/83RVFZ988tr4AllGJF9FJMSgjp2SI7ilR5rSY3ChQ88MD6AGB3metEvYFwDpug4l1m2r6xTdXZjIK1rWvUoi+/aC+r+LIke4xyIrYxkcYwFimgVrqeiD+orHxVqYKJJglKSN0SPJcBuXjqTHt5k/Bxfc61mCZTFKf6wjq/qO8U3fEt7DLOLmnfmQiMVRJ9NSY6s80vQhLgcUd3590dGDkl2Y1lHQ+FZMY5ofe6JFztIjrerHau3+pqGDTAXbB4znNVGTqoUqjG58EE+34IgMp5Bp19v5zThkQrug+HVcuuV6ol5qYbetCjLylKC/LDJJCVZPBM5x3VIU8lMcdaQXT8UceWBtLzjCsXq9Qy17DNIISWeygk1IaSptzdFsmpHdIFFLOWRkwfRYNzAYSS92mJ1e9Hz0Ina22XcBfNyuQxtAPhHVi1Eox6bTuNEdWiY9oKeD+EstJ/kErgeZVKQz2jCo9hvQ0ZB1ewP+pZ8sKk0G6Eoq+/Zqfw/K+CNXbtLuxuyY1LmN6WKNm+XCuoqQl6VCvh7iUtwTskQ=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
